name: 'acid'
description: 'Azure Container Instances Deployer.'
inputs:
  action:
    description: 'deploy/delete'
    required: true
  location:
    description: 'Azure region'
    required: true
    default: 'westeurope'
  subscription:
    description: 'Existing Azure subscription name'
    required: true
  rg:
    description: 'Existing Azure resource group name'
    required: true
  aci:
    description: 'Name of the Azure Container Instances to create'
    required: true
  image:
    description: 'Existing Docker image reference (fqdn/repository:tag)'
    required: true
  env_variables:
    description: 'Environment variables for container'
  env_secrets:
    description: 'Secret environment variables for container'
  vnet:
    description: 'Existing Azure virtual network name'
    required: true
  subnet:
    description: 'Existing Azure virtual network subnet name'
    required: true
  cpus:
    description: 'Number of CPU cores for container'
    required: true
    default: '1'
  memory_gbs:
    description: 'Memory (in gigabytes) for container'
    required: true
    default: '1.5'
  restart_policy:
    description: 'Container restart policy'
    default: 'OnFailure'
  creds:
    description: 'Azure Service Principal JSON object (= AZURE_CREDENTIALS)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.gh_repository }}
    - ${{ inputs.gh_pat }}
    - ${{ inputs.location }}
    - ${{ inputs.subscription }}
    - ${{ inputs.rg }}
    - ${{ inputs.aci }}
    - ${{ inputs.image }}
    - ${{ inputs.env_variables }}
    - ${{ inputs.env_secrets }}
    - ${{ inputs.vnet }}
    - ${{ inputs.subnet }}
    - ${{ inputs.labels }}
    - ${{ inputs.cpus }}
    - ${{ inputs.memory_gbs }}
    - ${{ inputs.creds }}
