name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4.1.4

    - name: Deploy ACI
      uses: alkue-com/acid@main
      with:
        action: deploy
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        image: ghcr.io/alkue-com/runner:latest
        vnet: ${{ secrets.VNET }}
        subnet: ${{ secrets.SUBNET }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        env_variables: LABELS=azure,dev NAME=acid
        env_secrets: GH_REPOSITORY=${{ github.repository }} GH_PAT=${{ secrets.GH_PAT }}

    - name: Delete ACI
      uses: alkue-com/acid@main
      with:
        action: delete
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        subnet:  ${{ secrets.SUBNET }}
