name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4.1.4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ACI
      id: deploy
      uses: alkue-com/acid@main
      with:
        action: deploy
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        file: aci.yaml
        env_variables: LABELS=acid NAME=nginx FILE=aci.yaml
