name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4.1.4

    - name: Deploy ACI
      uses: alkue-com/acid@main
      with:
        action: deploy
        gh_repository: ${{ github.repository }}
        gh_pat: ${{ secrets.GH_PAT }}
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        vnet: ${{ secrets.VNET }}
        subnet: ${{ secrets.SUBNET }}
        creds: $${ secrets.CREDS }}

    - name: Delete ACI
      uses: alkue-com/acid@main
      with:
        action: delete
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        creds: $${ secrets.CREDS }}
