name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ACI
      id: deploy
      uses: alkue-com/acid@main
      with:
        action: deploy
        subscription: ${{ secrets.SUBSCRIPTION }}
        location: ${{ secrets.LOCATION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        image: docker.io/hello-world:latest
        vnet: ${{ secrets.VNET }}
        subnet: ${{ secrets.SUBNET }}
        env_variables: LABELS=azure,🫠 NAME=hello
        env_secrets: REPOSITORY=${{ github.repository }}

    - name: Output subnet ACI was deployed to
      run: echo ${{ steps.deploy.outputs.subnet }}

    - name: Delete ACI
      id: delete
      uses: alkue-com/acid@main
      with:
        action: delete
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}

    - name: Output subnet ACI was deleted from
      run: echo ${{ steps.delete.outputs.subnet }}
