name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ACI
      id: deploy
      uses: alkue-com/acid@main
      with:
        action: deploy
        subscription: ${{ secrets.SUBSCRIPTION }}
        location: ${{ secrets.LOCATION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}
        image: docker.io/nginx:latest
        vnet: ${{ secrets.VNET }}
        subnet: ${{ secrets.SUBNET }}
        env_variables: LABELS=azure,acid NAME=nginx
        env_secrets: REPOSITORY=${{ github.repository }}
        az_args: --ports 80 8080 --assign-identity

    - name: Output vnet and subnet ACI was deployed to
      run: echo ${{ steps.deploy.outputs.vnet }} ${{ steps.deploy.outputs.subnet }}

    - name: Delete ACI
      if: always()
      id: delete
      uses: alkue-com/acid@main
      with:
        action: delete
        subscription: ${{ secrets.SUBSCRIPTION }}
        rg: ${{ secrets.RG }}
        aci: ${{ secrets.ACI }}

    - name: Output vnet and subnet ACI was deleted from
      if: always()
      run: echo ${{ steps.deploy.outputs.vnet }} ${{ steps.delete.outputs.subnet }}
